# Generated by Django 5.2.7 on 2025-11-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='default_dp.jpeg', null=True, upload_to='profile_pics/'),
        ),
    ]
