# Generated by Django 5.2.7 on 2025-11-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_facebook_event_notice_event_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('general', 'Hosted by University'), ('club', 'Hosted by a Club')], default='general', max_length=10),
        ),
    ]
