# Generated by Django 5.2.7 on 2025-11-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmembership',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
