# Generated by Django 5.2.7 on 2025-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_clubmembership_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
